name: Dependency review for pull requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-submission:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Cache build logic
        uses: actions/cache@v4
        with:
          path: gradle/build-logic/build
          key: build-logic-${{ hashFiles('gradle/build-logic/src/**', 'gradle/build-logic/build.gradle.kts','gradle/build-logic/settings.gradle.kts') }}
      - uses: gradle/actions/dependency-submission@v4
        with:
          cache-encryption-key: ${{ secrets.CC }}

      - uses: actions/dependency-review-action@v4
        if: github.event_name == 'pull_request'
